### ISSUE TITLE
Future Entitas versions compatibility

### ISSUE THREAD

**Issue by c0ffeeartc** [c0ffeeartc/GenEntitas#1]
Hi,
this generator started as alternative to Entitas unity generator. At the beginning I didn't understand much how unity generator works, so I rewrote some parts of it, which makes it tied to a specific Entitas version.

Now i think it's possible to make mostly version independent generator by wrapping some public methods from Entitas dlls. If you have time and desire to do so, please write such wrapper systems as a separate set of systems, then we can switch this generator systems with new ones and get version independent results.

Please share pros and cons, other ideas on how to achieve best results with ECS structure.

**Comment by c0ffeeartc** [comment]
Another solution could be separate dll with components and systems per Entitas version for identical Entitas/GenEntitas generation results. Each dll would `#define` macro with version id and other plugins could relate to them

**Comment by OneYoungMean** [comment]
I guess this interesting software will give me some help.
 but honestly for the beginner, trying to collect tutorials from someone else's software is too difficult.
So can I ask for a simple explanation or some description pictures?the readme is too abstract and complex for me, I can't understand it accurately.
Thanks for your notice it.

**Comment by c0ffeeartc** [comment]
Hello, thanks for your interest.
I'll write reasons to use and step by step here, and if it turns out helpful will incorporate parts of explanation into readme.

Entitas already has free unity generator, and payed roslyn generator, if they work well for you I'd recommend using them.
Main reasons to use GenEntitas would be:
  - Run free generator from console
  - Run roslyn generator for free. It's less tested and much slower because lacks server mode and has to recompile solution on every run.
  - Add custom generator more easily
  - Architecture is based on Entitas and familiar to average Entitas user. Easier to fix/hack/extend generator

Steps to use:
  - Clone repository
  - Open solution in IDE ( I use Rider ). It should download NuGet packages
  - Build solution
  - If compilation is not successful find/create issue in github repository
  - manually create settings file. Use `pathToClonedRepo/GenComps.settings` as reference
  - add SearchPaths option to settings, it's for paths to folders of dlls outside project. In OSX it may look like this for Unity2018.2.15f1 `SearchPaths = /Applications/Unity/Hub/Editor/2018.2.15f1/Unity.app/Contents/Managed/UnityEngine,/Applications/Unity/Hub/Editor/2018.2.15f1/Unity.app/Contents/Managed,/Applications/Unity/Hub/Editor/2018.2.15f1/Unity.app/Contents/Mono/lib/mono/unity,/Applications/Unity/Hub/Editor/2018.2.15f1/Unity.app/Contents/UnityExtensions/Unity/GUISystem
` 
  - in osx from shell call `mono pathToClonedRepo/GenEntitas/bin/Debug/GenEntitas.exe pathToSettingsFile`
  - it should write some info into console and create generated files

If you have additional questions please create separate issue and I'll try to answer them.
